// <auto-generated />
namespace HospitalProjectMackenzie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addforeignkeyfordepartmentandroom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addforeignkeyfordepartmentandroom));
        
        string IMigrationMetadata.Id
        {
            get { return "202303262040245_add-foreign-key-for-department-and-room"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
